// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MNxHDMfMIqJ9ihRsRQc06HZ4_IjaeJg',
    appId: '1:672775881527:web:4644b2f80de98a4b1250b2',
    messagingSenderId: '672775881527',
    projectId: 'flutterfirebase-8f297',
    authDomain: 'flutterfirebase-8f297.firebaseapp.com',
    storageBucket: 'flutterfirebase-8f297.appspot.com',
    measurementId: 'G-KLE5GS0VMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHw0pcCAHNNyNS23AAdFGOeS1j_wrkco',
    appId: '1:672775881527:android:d8ff02970baa5cf11250b2',
    messagingSenderId: '672775881527',
    projectId: 'flutterfirebase-8f297',
    storageBucket: 'flutterfirebase-8f297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHcdltU_pmXD1HYroszUhfoy7nLxcm-f4',
    appId: '1:672775881527:ios:fe6b62676ecf3d231250b2',
    messagingSenderId: '672775881527',
    projectId: 'flutterfirebase-8f297',
    storageBucket: 'flutterfirebase-8f297.appspot.com',
    iosBundleId: 'com.example.flutterCertamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHcdltU_pmXD1HYroszUhfoy7nLxcm-f4',
    appId: '1:672775881527:ios:1367c4a4c5b69d3c1250b2',
    messagingSenderId: '672775881527',
    projectId: 'flutterfirebase-8f297',
    storageBucket: 'flutterfirebase-8f297.appspot.com',
    iosBundleId: 'com.example.flutterCertamen.RunnerTests',
  );
}
